//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTrackingSystem.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Shift = new HashSet<Shift>();
        }
    
        public int EmployeeID { get; set; }
        public int ProdmaID { get; set; }
        public string Password { get; set; }
        public int UserType { get; set; }
        public string NationalityID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int Department { get; set; }
        public string State { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public System.TimeSpan NormalShiftTime { get; set; }
        public string Total { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual UserType UserType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shift> Shift { get; set; }
    }
}
