//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTrackingSystem.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int ShiftID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> ShiftDate { get; set; }
        public Nullable<System.TimeSpan> EntryTime { get; set; }
        public Nullable<System.TimeSpan> ExitTime { get; set; }
        public Nullable<System.TimeSpan> WorkTime { get; set; }
        public Nullable<System.TimeSpan> OverTime { get; set; }
        public Nullable<System.TimeSpan> MissingTime { get; set; }
        public string Period { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
